name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LATEST_TAG: curl-http3:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.LATEST_TAG }}
    - name: Test
      run: docker run --rm ${{ env.LATEST_TAG }} --http3-only -v https://google.com
